# Generated by Django 6.0.1 on 2026-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
